### ISSUE TITLE
Request works, but dropdown is empty

### ISSUE THREAD

**Issue by marcus-at-localhost** [laraluke/statamic-api-select#3]
I retrieve Data from a Statamic Taxonomy, but the dropdown is empty, even if it seems that data was retrive sucessfully.

Any idea what's going on here?

![image](https://user-images.githubusercontent.com/1337223/94484175-47903c80-01dc-11eb-8f67-8414fcd4d7cd.png)

**Comment by laraluke** [comment]
Initial impressions are that the component props look fine.

Are you seeing any errors in the console?

**Comment by marcus-at-localhost** [comment]
No, no errors in the console. 

could it be the `::` in the keys? That would be odd, but who knows?!

**Comment by laraluke** [comment]
Potentially! Have you tried testing values without `::`? (from a mock API endpoint for example)

**Comment by marcus-at-localhost** [comment]
It's not the `::` :)

here is my field definition incl. a stripped down api endpoint: <https://run.mocky.io/v3/ccc4197d-d6c5-432d-9f3b-f961497d63dc>

```json
{
  "data": [
    {
      "id": "branches__werk-N",
      "template": "career/index",
      "title": "Werk N-Buchholz",
      "updated_at": "2020-09-28T08:13:04.000000Z",
    },
  ],
  "links": {
  }
}
```

```yaml
        handle: api_select
        field:
          endpoint_type: url
          endpoint: 'https://run.mocky.io/v3/ccc4197d-d6c5-432d-9f3b-f961497d63dc'
          cache_minutes: 0
          data_set_key: data
          item_key: id
          item_label: title
          clearable: false
          multiple: false
          searchable: true
          cast_booleans: false
          display: 'API Select'
          type: api_select
          icon: select
          listable: hidden
```

Of course it doesn't make sense to call statamic taxonomy api since it's available, but it was the first endpoint to test you field - mybe I setup something wrong?!
